services:
  - name: submission-webhook
    type: web
    env: node
    plan: free
    buildCommand: cd apps/submission-webhook && npm install && npm run build
    startCommand: cd apps/submission-webhook && npm start
    branch: main