services:
  - name: submission-webhook
    type: web
    env: node
    plan: free
    buildCommand: 
    - npm install 
    - cd packages/db && npm install && npm run postinstall 
    - cd ../../
    - cd apps/submission-webhook && npm install && npm run build && npm run postbuild
    startCommand: cd apps/submission-webhook && npm run start
    branch: main