services:
  - name: submission-webhook
    type: web
    env: node
    plan: free
    buildCommand: 
    - npm install 
    - cd packages/db && npm install && npm run postinstall 
    - cd ../../
    - cd apps/submission-webhook
- npm install
- npx esbuild src/index.ts --bundle --platform=node --outfile=dist/index.js
- cp node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node dist/ && chmod +x dist/libquery_engine-debian-openssl-1.1.x.so.node
    startCommand: cd apps/submission-webhook && npm run start
    branch: main