services:
  - name: submission-webhook
    type: web
    env: node
    plan: free
    buildCommand: 
    - npm install 
    - cd apps/packages/prisma && npx prisma generate
    - cd ../../../
    - cd apps/submission-webhook && npm install && npm run build 
    startCommand: cd apps/submission-webhook && npm start
    branch: main